- name: Testing a condition
  hosts: all
  vars:
    my_service: Web-Server
  tasks:
  - name: Install "{{ my_service }}" with sub features and management tools
    win_feature:
      name: "{{ my_service }}"
      state: present
      include_sub_features: yes
      include_management_tools: yes
    when: ansible_facts['architecture'] == "64-bit"
