- name: Testing Handlers
  hosts: all
  force_handlers: true
  tasks:
  - name: Install Dotnet4.6.1
    win_chocolatey:
      name: dotnet4.6.1
      state: present
    notify:
    - reboot server
  - name: Install notafeature with sub features and management tools
    win_feature:
      name: notafeature
      state: present
      include_sub_features: yes
      include_management_tools: yes
  handlers:
  - name: reboot server
    win_reboot:
